const animals = [
  'Ant',
  'Aquarium',
  'Badger',
  'Bat Face',
  'Bear',
  'Beaver',
  'Bee',
  'Bird',
  'Bug',
  'Bull',
  'Bumblebee',
  'Butterfly',
  'Cat Footprint',
  'Cat',
  'Caterpillar',
  'Chicken',
  'Clown Fish',
  'Corgi',
  'Cow',
  'Crab',
  'Deer',
  'Dinosaur',
  'Dog Park',
  'Dog',
  'Dolphin',
  'Dragonfly',
  'Duck',
  'Elephant',
  'Falcon',
  'Fish Food',
  'Fish',
  'Fly',
  'Frog',
  'Giraffe',
  'Gorilla',
  'Grasshopper',
  'Hornet Hive',
  'Hornet',
  'Horse',
  'Hummingbird',
  'Insect',
  'Kangaroo',
  'Kiwi Bird',
  'Ladybird',
  'Leopard',
  'Lion',
  'Llama',
  'Mite',
  'Mosquito',
  'Octopus',
  'Panda',
  'Pig With Lipstick',
  'Pig',
  'Prawn',
  'Puffin Bird',
  'Rabbit',
  'Rhinoceros',
  'Seahorse',
  'Shark',
  'Sheep',
  'Snail',
  'Spider',
  'Starfish',
  'Stork',
  'Tentacles',
  'Turtle',
  'Unicorn',
  'Wasp',
  'Whale',
  'Wolf',
]

const cinema = [
  'Action 2',
  'Action',
  'Add Image',
  'Add Ticket',
  'Advertising',
  'Alien',
  'Animation',
  'Apple TV',
  'Asteroid',
  'Astronaut',
  'Audience',
  'Av Receiver',
  'Ballet Shoes',
  'Binoculars',
  'Bunch Flowers',
  'Cable Release',
  'Camcorder Pro',
  'Camcorder',
  'Camera Addon',
  'Camera Automation',
  'Camera Identification',
  'Camera',
  'Captain America',
  'Channel Mosaic',
  'Clapperboard',
  'Close Up Mode',
  'Comedy 2',
  'Comedy',
  'Comet',
  'Compact Camera',
  'Crime',
  'Dance With Devil',
  'Delete Ticket',
  'Detective',
  'Documentary',
  'Drama',
  'Edit Image',
  'Facepalm',
  'Family',
  'Fantasy',
  'Film Noir',
  'Film Reel',
  'Film',
  'Gallery',
  'Grey',
  'Historical',
  'Horror',
  'Idea',
  'IMDb',
  'Integrated Webcam',
  'Iron Man',
  'Landscape',
  'Living Room',
  'Martian',
  'Moon',
  'Multiple Cameras',
  'Music',
  'Musical',
  'News',
  'Night Landscape',
  'Night Portrait',
  'Ninja Turtle',
  'No Idea',
  'Novel',
  'Old Time Camera',
  'Opera Glasses',
  'Panorama',
  'Planet',
  'Podium With Audience',
  'Podium With Speaker',
  'Portrait Mode',
  'Predator',
  'Puzzle',
  'Rating',
  'Remove Image',
  'Rotate Camera',
  'Sci Fi',
  'Scream',
  'SDTV',
  'Selfie',
  'Short',
  'SLR Back Side',
  'Speaker',
  'Sport',
  'Sports Mode',
  'Stack of Photos',
  'Starred Ticket',
  'Start',
  'Steve Jobs',
  'Switch Camera',
  'Theatre Mask',
  'Thriller',
  'Ticket',
  'TV',
  'Undergo Insomnia',
  'Video File',
  'Video Projector',
  'Watch TV In Bed',
  'Western',
  'Widescreen TV',
]

const card = {
  size: 400,
  positions: [
    {"x":140.16,"y":200.3,"r":31.77,"size":44.92},
    {"x":316,"y":249.86,"r":73.36,"size":103.74},
    {"x":189.51,"y":302.19,"r":63.53,"size":89.85},
    {"x":68.64,"y":146.07,"r":58,"size":82.02},
    {"x":74.86,"y":261.89,"r":58,"size":82.02},
    {"x":279.96,"y":107.64,"r":73.36,"size":103.74},
    {"x":212.93,"y":200.3,"r":41.01,"size":58},
    {"x":166.71,"y":132.55,"r":41.01,"size":58},
  ],
}

const smileys = [
  'angry', 'happy', 'joy', 'love',
  'shy', 'sleepy', 'surprise', 'wink',
]

export default { animals, cinema, card, smileys }
